# Generated by Django 4.0.4 on 2022-07-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('mobile_number', models.IntegerField()),
                ('marks', models.FloatField()),
            ],
        ),
    ]
